import 'dart:async';

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'package:gitty/app.dart';
import 'package:gitty/core/console/console_log_service.dart';
import 'package:gitty/core/firebase/remote_config_service.dart';
import 'package:gitty/core/network/ssl/ssl_pinning_service.dart';

// Generated by FlutterFire CLI — add your own google-services.json / GoogleService-Info.plist
// import 'firebase_options.dart';

Future<void> main() async {
  // Catch all uncaught Flutter/Dart errors and log them
  await runZonedGuarded(
    _bootstrap,
    (error, stack) {
      debugPrint('[Gitty] Uncaught error: $error');
      debugPrintStack(stackTrace: stack);
    },
  );
}

Future<void> _bootstrap() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ── System UI ────────────────────────────────────────────────────────────
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.dark,
      systemNavigationBarColor: Colors.transparent,
    ),
  );
  SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);
  SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // ── Firebase ─────────────────────────────────────────────────────────────
  await Firebase.initializeApp(
      // options: DefaultFirebaseOptions.currentPlatform, // uncomment after FlutterFire CLI
      );

  // ── SSL Pinning ──────────────────────────────────────────────────────────
  await SslPinningService.initialize();

  // ── Riverpod container (for pre-run initialization) ───────────────────────
  final container = ProviderContainer();

  // ── Remote Config + Kill Switch ───────────────────────────────────────────
  try {
    final remoteConfig = container.read(remoteConfigServiceProvider);
    await remoteConfig.initialize();
  } on Exception catch (e) {
    // Non-fatal — app runs with defaults if Remote Config is unavailable
    debugPrint('[Gitty] Remote Config init failed: $e');
  }

  // ── Global error handling via FlutterError ───────────────────────────────
  final originalOnError = FlutterError.onError;
  FlutterError.onError = (details) {
    // Log to Developer Console
    try {
      container.read(consoleLogServiceProvider).error(
            '${details.exceptionAsString()}',
            tag: 'FlutterError',
            error: details.exception,
            stackTrace: details.stack,
          );
    } on Exception {
      // Ignore logging errors
    }

    originalOnError?.call(details);
  };

  // ── Run App ──────────────────────────────────────────────────────────────
  runApp(
    UncontrolledProviderScope(
      container: container,
      child: const GittyApp(),
    ),
  );
}
